name: Build & Push Docker Image after modifying the api

on:
    push:
      paths:
        - 'app/**'  # Exécuter le workflow uniquement si le code du conteneur est modifié

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  APP_NAME: app # Nom du dossier contenant le code de l'API
  DOCKER_IMAGE_PATH: hedredo/segmentation_api:latest

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.16'

      # Étape 3 : Installer les dépendances du conteneur à tester
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./${{ env.APP_NAME }}/requirements.txt

      # Étape 4 : Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_PATH }} ./${{ env.APP_NAME }}

      # Étape 5 : Docker login using the Docker login action
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Étape 6 : Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_IMAGE_PATH }}